# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89611180b055deb02ed0ed764afa70050516d9a735b69c6e549c935cc4c38be1a4bcfaa6ae72fa29528e13062c4367149fe6541c6675bd20ec5e74eddb90272

test:
  secret_key_base: 1c1bb49084bfb081777dd2ec736514bd33a2569805ad113be123ba6e36fca704d2da55c0f6637e0f1df2f4315e521eebe2abc2866c34c90ef2917fe8a6ccccda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
